CREATE OR REPLACE PROCEDURE SC_PROC_DELETE_TASK 
(
  OLDID IN NUMBER 
) IS
  OLDPOSITION NUMBER;
  OLDSTATE VARCHAR2(50);
  OLDIDSPRINT NUMBER;
  
BEGIN
  SELECT SC_TASK.POSITION, SC_TASK.STATE, SC_TASK.IDSPRINT INTO OLDPOSITION, OLDSTATE, OLDIDSPRINT FROM SC_TASK WHERE SC_TASK.ID = OLDID;
  DELETE FROM SC_TASK WHERE SC_TASK.ID = OLDID;
  FOR CURRENTTASK IN (SELECT ID, POSITION FROM SC_TASK WHERE SC_TASK.ID != OLDID AND (SC_TASK.STATE = OLDSTATE) AND SC_TASK.IDSPRINT = OLDIDSPRINT AND SC_TASK.POSITION > OLDPOSITION) LOOP
    UPDATE SC_TASK SET POSITION = POSITION - 1 WHERE CURRENTTASK.ID = ID;
  END LOOP;
  COMMIT;
END SC_PROC_DELETE_TASK;
