DROP SEQUENCE SC_SEQ_USER;
DROP SEQUENCE SC_SEQ_TASK;
DROP SEQUENCE SC_SEQ_PROJECT;
DROP SEQUENCE SC_SEQ_SPRINT;
DROP SEQUENCE SC_SEQ_PROJECTLOGENTRY;

CREATE SEQUENCE SC_SEQ_USER;
CREATE SEQUENCE SC_SEQ_TASK;
CREATE SEQUENCE SC_SEQ_PROJECT;
CREATE SEQUENCE SC_SEQ_SPRINT;
CREATE SEQUENCE SC_SEQ_PROJECTLOGENTRY;
