DROP TABLE SC_USER CASCADE CONSTRAINTS;
DROP TABLE SC_SPRINT CASCADE CONSTRAINTS;
DROP TABLE SC_TASK CASCADE CONSTRAINTS;
DROP TABLE SC_PROJECT CASCADE CONSTRAINTS;
DROP TABLE SC_TEAMMEMBER CASCADE CONSTRAINTS;
DROP TABLE SC_PROJECTLOGENTRY CASCADE CONSTRAINTS;

CREATE TABLE SC_USER(
 ID NUMBER PRIMARY KEY,
 USERNAME VARCHAR2(30) UNIQUE,
 PASSWORD VARCHAR2(30)
);

CREATE TABLE SC_TASK(
 ID NUMBER PRIMARY KEY,
 IDRESPONSIBLE NUMBER,
 IDVERIFY NUMBER,
 NAME VARCHAR2(30),
 INFO VARCHAR2(500),
 REJECTIONS NUMBER,
 STATE VARCHAR2(20) CHECK(STATE = 'PRODUCT_BACKLOG' OR STATE = 'SPRINT_BACKLOG' OR STATE = 'IN_PROGRESS' OR STATE = 'TO_VERIFY' OR STATE = 'DONE'),
 POSITION NUMBER,
 IDSPRINT NUMBER,
 IDPROJECT NUMBER,
 CONSTRAINT FK_USERSTORY_RESPONSIBLE FOREIGN KEY(IDRESPONSIBLE) REFERENCES SC_USER(ID),
 CONSTRAINT FK_USERSTORY_VERIFY FOREIGN KEY(IDVERIFY) REFERENCES SC_USER(ID),
 CHECK((IDSPRINT IS NULL AND STATE = 'PRODUCT_BACKLOG') OR (IDSPRINT IS NOT NULL AND STATE != 'PRODUCT_BACKLOG'))
);

CREATE TABLE SC_PROJECT(
 ID NUMBER PRIMARY KEY,
 NAME VARCHAR2(30),
 IDPRODUCTOWNER NUMBER,
 IDCURRENTSPRINT NUMBER,
 CONSTRAINT FK_PROJECT_USER FOREIGN KEY(IDPRODUCTOWNER) REFERENCES SC_USER(ID) 
);

CREATE TABLE SC_SPRINT(
  ID NUMBER PRIMARY KEY,
  SPRINTNUMBER NUMBER,
  STARTDATE DATE,
  DEADLINE DATE,
  IDPROJECT NUMBER,
  CONSTRAINT FK_SPRINT_PROJECT FOREIGN KEY(IDPROJECT) REFERENCES SC_PROJECT(ID)
);

CREATE TABLE SC_TEAMMEMBER(
 IDUSER NUMBER,
 IDPROJECT NUMBER,
 CONSTRAINT PK_TEAMMEMBER PRIMARY KEY(IDUSER,IDPROJECT),
 CONSTRAINT FK_TEAMMEMBER_USER FOREIGN KEY(IDUSER) REFERENCES SC_USER(ID),
 CONSTRAINT FK_TEAMMEMBER_PROJECT FOREIGN KEY(IDPROJECT) REFERENCES SC_PROJECT(ID)
);

CREATE TABLE SC_LASTUPDATE( 
  IDPROJECT NUMBER PRIMARY KEY, 
	 DATUM DATE, 
  CONSTRAINT FK_PROJECT_LASTUPDATE FOREIGN KEY (IDPROJECT) REFERENCES SC_PROJECT (ID)
);

ALTER TABLE SC_PROJECT
  ADD CONSTRAINT FK_PROJECT_SPRINT FOREIGN KEY(IDCURRENTSPRINT) REFERENCES SC_SPRINT(ID);
ALTER TABLE SC_TASK
  ADD  CONSTRAINT FK_USERSTORY_SPRINT FOREIGN KEY(IDSPRINT) REFERENCES SC_SPRINT(ID);
ALTER TABLE SC_TASK
  ADD  CONSTRAINT FK_USERSTORY_PROJECT FOREIGN KEY(IDPROJECT) REFERENCES SC_PROJECT(ID);
