INSERT INTO SC_USER VALUES(NULL,'Webi','webi1234');
INSERT INTO SC_USER VALUES(NULL,'Samuel','sam1234');
INSERT INTO SC_USER VALUES(NULL,'Paul','paul1234');
INSERT INTO SC_USER VALUES(NULL,'Simon','simon1234');
INSERT INTO SC_USER VALUES(NULL,'Martin','tino1234');
INSERT INTO SC_USER VALUES(NULL,'Nico','nico1234');

INSERT INTO SC_PROJECT VALUES(NULL,'Scrumble',24,NULL);
INSERT INTO SC_PROJECT VALUES(NULL,'Sportify',27,NULL);
INSERT INTO SC_PROJECT VALUES(NULL,'Caplin-DA',28,NULL);
INSERT INTO SC_PROJECT VALUES(NULL,'SQL-Developer Ocepek',23,NULL);

INSERT INTO SC_SPRINT VALUES(NULL,1,SYSDATE ,SYSDATE + 100,22);
INSERT INTO SC_SPRINT VALUES(NULL,2,SYSDATE + 101,SYSDATE + 200,22);
INSERT INTO SC_SPRINT VALUES(NULL,1,SYSDATE - 100,SYSDATE - 1,23);
INSERT INTO SC_SPRINT VALUES(NULL,2,SYSDATE - 200,SYSDATE - 101,23);
INSERT INTO SC_SPRINT VALUES(NULL,1,SYSDATE - 100,SYSDATE - 50,24);
INSERT INTO SC_SPRINT VALUES(NULL,2,SYSDATE - 50,SYSDATE - 1,24);
INSERT INTO SC_SPRINT VALUES(NULL,1,SYSDATE - 1000,SYSDATE - 500,25);
INSERT INTO SC_SPRINT VALUES(NULL,2,SYSDATE - 499,SYSDATE,25);

INSERT INTO SC_TEAMMEMBER VALUES(23,22);
INSERT INTO SC_TEAMMEMBER VALUES(24,22);
INSERT INTO SC_TEAMMEMBER VALUES(25,22);
INSERT INTO SC_TEAMMEMBER VALUES(26,22);

INSERT INTO SC_TEAMMEMBER VALUES(23,23);
INSERT INTO SC_TEAMMEMBER VALUES(24,23);
INSERT INTO SC_TEAMMEMBER VALUES(25,23);
INSERT INTO SC_TEAMMEMBER VALUES(26,23);
INSERT INTO SC_TEAMMEMBER VALUES(27,23);

INSERT INTO SC_TEAMMEMBER VALUES(23,24);
INSERT INTO SC_TEAMMEMBER VALUES(24,24);
INSERT INTO SC_TEAMMEMBER VALUES(28,24);

INSERT INTO SC_TEAMMEMBER VALUES(23,25);
INSERT INTO SC_TEAMMEMBER VALUES(25,25);
INSERT INTO SC_TEAMMEMBER VALUES(27,25);

INSERT INTO SC_TASK VALUES(NULL,23,26,'Testdata','Adding Testdata to Database',0,'TO_VERIFY',1,9,22);
INSERT INTO SC_TASK VALUES(NULL,24,25,'WPF','Creating a beatiful WPF Application',0,'IN_PROGRESS',1,9,22);
INSERT INTO SC_TASK VALUES(NULL,25,23,'Android','Creating a beautiful Android Application',0,'IN_PROGRESS',2,10,22);
INSERT INTO SC_TASK VALUES(NULL,26,24,'Webservice','Creating a beautifully running Webservice to get a Döner from Sam',0,'IN_PROGRESS',3,10,22);

INSERT INTO SC_TASK VALUES(NULL,23,27,'Scrumboard','Making a Scrum Board',0,'DONE',1,11,23);
INSERT INTO SC_TASK VALUES(NULL,24,25,'Backend','Making a the backend',0,'DONE',2,11,23);
INSERT INTO SC_TASK VALUES(NULL,25,23,'Frontend','Making the frontend',0,'DONE',1,12,23);
INSERT INTO SC_TASK VALUES(NULL,27,26,'Webservice','Creating a beautifully running Webservice',0,'DONE',2,12,23);

INSERT INTO SC_TASK VALUES(NULL,23,28,'CRM System','Reworking the CRM System',0,'DONE',1,13,24);
INSERT INTO SC_TASK VALUES(NULL,28,24,'Streamlink','Streamlink stuff',0,'DONE',1,14,24);

INSERT INTO SC_TASK VALUES(NULL,23,26,'SQL_Developen','Develop SQL to make Ozepek happy',0,'DONE',1,15,25);
INSERT INTO SC_TASK VALUES(NULL,26,27,'More SQL','MORE SQL',0,'DONE',2,15,25);
INSERT INTO SC_TASK VALUES(NULL,27,26,'Even More SQL','MAXIMUM SQL Development',0,'DONE',1,16,25);

INSERT INTO SC_TASK VALUES(NULL,23,25,'Backlog Entries','Creating a beautifully Backlog Entry',0,'PRODUCT_BACKLOG',NULL,NULL,22);
INSERT INTO SC_TASK VALUES(NULL,24,27,'Backlog Entries','Creating a beautifully Backlog Entry',0,'PRODUCT_BACKLOG',NULL,NULL,23);
INSERT INTO SC_TASK VALUES(NULL,28,23,'Backlog Entries','Creating a beautifully Backlog Entry',0,'PRODUCT_BACKLOG',NULL,NULL,24);
INSERT INTO SC_TASK VALUES(NULL,27,23,'Backlog Entries','Creating a beautifully Backlog Entry',0,'PRODUCT_BACKLOG',NULL,NULL,25);

UPDATE SC_PROJECT SET IDCURRENTSPRINT = 10 WHERE ID = 22;
UPDATE SC_PROJECT SET IDCURRENTSPRINT = 12 WHERE ID = 23;
UPDATE SC_PROJECT SET IDCURRENTSPRINT = 14 WHERE ID = 24;
UPDATE SC_PROJECT SET IDCURRENTSPRINT = 16 WHERE ID = 25;
