CREATE OR REPLACE TRIGGER SC_TRG_USER
  BEFORE INSERT ON SC_USER
  FOR EACH ROW
BEGIN
  SELECT SC_SEQ_USER.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER SC_TRG_TASK
  BEFORE INSERT ON SC_TASK
  FOR EACH ROW
BEGIN
  SELECT SC_SEQ_TASK.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER SC_TRG_PROJECT
  BEFORE INSERT ON SC_PROJECT
  FOR EACH ROW
BEGIN
  SELECT SC_SEQ_PROJECT.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER SC_TRG_SPRINT
  BEFORE INSERT ON SC_SPRINT
  FOR EACH ROW
BEGIN
  SELECT SC_SEQ_SPRINT.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;
